version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: cay-ocagi-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cay-ocagi
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: cay-ocagi-backend
    restart: always
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/cay-ocagi?authSource=admin
      JWT_SECRET: your-secret-key-here
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: cay-ocagi-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data: