version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: arac_user
      POSTGRES_PASSWORD: arac_password
      POSTGRES_DB: arac_filo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://arac_user:arac_password@postgres/arac_filo_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-here
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data: