version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mezarlik-postgres
    environment:
      POSTGRES_USER: mezarlik_user
      POSTGRES_PASSWORD: mezarlik_pass
      POSTGRES_DB: mezarlik_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mezarlik-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mezarlik-backend
    environment:
      DATABASE_URL: postgresql://mezarlik_user:mezarlik_pass@postgres:5432/mezarlik_db
      SECRET_KEY: your-secret-key-here-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mezarlik-network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mezarlik-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mezarlik-network

networks:
  mezarlik-network:
    driver: bridge

volumes:
  postgres_data: